/*
 * This source file was generated by the Gradle 'init' task
 */
package org.quickfix;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

class PerformanceTestAppTest {
    @Disabled
    @Test void test() {

    }
}
